name: Bug report
description: Something isn't working
title: 🐛 <title>
labels:
  - status:needs-triage
  - type:fix
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue you are facing.
        Complete the form below to ensure the necessary details are captured to assist you.
  - id: prerequisites
    type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: read documentation
          required: true
        - label: searched open issues for existing bug report
          required: true
        - label: searched closed issues for solution(s) or feedback
          required: true
  - id: current-behavior
    type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing
    validations:
      required: true
  - id: repro
    type: textarea
    attributes:
      label: Reproduction
      description: |
        [Minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
    validations:
      required: true
  - id: expected-behavior
    type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen
    validations:
      required: true
  - id: homebrew-version
    type: textarea
    attributes:
      label: Homebrew version
      description: '`brew --version` output'
      placeholder: |
        ```sh
        Homebrew 3.5.9
        Homebrew/homebrew-core (git revision 191ec7ef868; last commit 2022-08-21)
        Homebrew/homebrew-cask (git revision 510c1738e3; last commit 2022-08-21)
        ```
    validations:
      required: true
  - id: node-version
    type: input
    attributes:
      label: Node.js version
      description: '`node --version` output'
      placeholder: v16.16.0
    validations:
      required: true
  - id: additional-context
    type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other details about the problem here. Include links as necessary (e.g. relevant docs, issues, pull requests, etc)
    validations:
      required: false
