# Continuous Integration
#
# References:
#
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#push
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# - https://github.com/actions/checkout
# - https://github.com/hmarr/debug-action

---
name: ci
on:
  pull_request:
  push:
    branches:
      - feat/**
      - hotfix/**
      - main
  workflow_dispatch:
env:
  HUSKY: 0
  REF: ${{ github.head_ref || github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v2.1.0
      - id: checkout
        name: Checkout ${{ env.REF }}
        uses: actions/checkout@v3.5.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: yarn
        name: Install dependencies
        if: github.actor != 'dependabot[bot]'
        run: yarn
      - id: yarn-dependabot
        name: Install dependencies for dependabot
        if: github.actor == 'dependabot[bot]'
        run: yarn --no-immutable
      - id: format
        name: Check code formatting
        run: yarn check:format
      - id: lint
        name: Check lint status
        run: yarn check:lint
      - id: spelling
        name: Check spelling
        run: yarn check:spelling
